# PUT YOUR GITHUB ACTION WORKFLOW HERE

name: GitHub Action

on:
  pull_request:
    branches: [main, github_action]
  # PUT A TRIGGER HERE

jobs:
  job-name: # CALL THE JOB SOMETHING
    runs-on: ubuntu-latest  
    
    steps:
        # PUT A STEP HERE 'uses' or 'run'
